# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnvanilla' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnvanilla

  # Flexbox Layout Manager Used By React Natve
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'

  # React Native
  pod 'React', path: '../node_modules/react-native', subspecs: [
    # Comment out any unneeded subspecs to reduce bundle size.
    #'BatchedBridge',
    'Core',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTBlob',
    #'RCTCameraRoll',
    #'RCTGeolocation',
    #'RCTImage',
    #'LinkingIOS',
    'RCTNetwork',
    #'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    #'RCTVibration',
    #'RCTWebSocket',
  ]

  #pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-camera', subspecs: ['RCT', 'RN', 'FaceDetector'], path: '../node_modules/react-native-camera'

  target 'rnvanillaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnvanilla-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnvanilla-tvOS

  target 'rnvanilla-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
